version: '3.1'

services:
  royal:
    image: dockerklint/kim_royal:latest
    container_name: kim_royal
    restart: always
    networks: 
      - kimnet
    ports:
      - "8080:8080"
    volumes:
      - ~/data/kim/:/data/
    environment:
      external_ip: 192.168.3.201
  gateway:
    image: dockerklint/kim_gateway:latest
    container_name: kim_gateway
    restart: always
    networks: 
      - kimnet
    ports:
      - "8000:8000"
    volumes:
      - ~/data/kim/:/data/
    environment:
      external_ip: 192.168.3.201
  server:
    image: dockerklint/kim_server:latest
    container_name: kim_server
    restart: always
    networks: 
      - kimnet
    ports:
      - "8005:8005"
    volumes:
      - ~/data/kim/:/data/
    environment:
      external_ip: 192.168.3.201
networks:
  kimnet: {}